### PR TITLE
AUTH-257 support extraClients and roles for them

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Looking to use this to move ahead with https://github.com/Activiti/activiti-cloud-charts/pull/51

Addresses the comments on https://github.com/Alfresco/alfresco-identity-service/pull/80 - apologies for having to close that, I was having trouble with the CLA

### CODE REVIEW

**Comment by ryandawsonuk** [comment]
Is there anything we can do to help move this along?

My understanding is that all of the comments from @rgauss and @jottley on https://github.com/Alfresco/alfresco-identity-service/pull/80 have been addressed by reducing the scope of the changes.

**Comment by rgauss** [comment]
We needed to get the current issue into the sprint and make sure the build is green before merging, still working on that.

**Comment by ryandawsonuk** [comment]
Actually I just tried testing this again and am struggling to get this version working [like the previous version was](https://github.com/ryandawsonuk/alfresco-identity-service/commit/92f05b3a60ec72787baa854781813b4570fbc662). Will carry on testing but best not to merge until it is resolved.

**Comment by ryandawsonuk** [comment]
OK it does work fine, I was just getting confused about at what level the entry goes in the values.yaml. It goes at the base level, parallel to realm. A test entry could be:

```
extraClients:
  activiti:
    clientId: activiti
    enabled: true
    publicClient: true
    redirectUris:
      - "localhost:*"
    webOrigins:
      - "localhost:*"
    directAccessGrantsEnabled: true
    implicitFlowEnabled: true
    clientRoles:
      - name: test_role
        scopeParamRequired: false
        composite: false
        clientRole: true
```

**Comment by rgauss** [comment]
Hmm, I think we want those defined within the `alfresco` realm in values, so perhaps these should be updated to `.Values.realm.alfresco.extraClients` and `.Values.realm.alfresco.extraClientRoles`.

**Comment by ryandawsonuk** [comment]
Yeah that makes sense, I'll try to move them.

**Comment by ryandawsonuk** [comment]
Actually I'm going to have to stop working on this for a while. Advice from @salaboy is that there are other things which are higher priority for activiti right now.

**Comment by salaboy** [comment]
@ryandawsonuk @rgauss we need an issue in activiti/activiti

**Comment by ryandawsonuk** [comment]
@salaboy do you mean one specifically for the change to AIS? I'd been working from https://github.com/Activiti/Activiti/issues/2450

**Comment by salaboy** [comment]
@ryandawsonuk that is moved to 7.1.0.M2 so we need to understand what the priority of this issue.

**Comment by ryandawsonuk** [comment]
@rgauss have now [pushed the requested changes](https://github.com/Alfresco/alfresco-identity-service/pull/83/commits/51bcb4c815cbfa1fdf831c64e2e52dfb47fa02b1) and [updated the PR on activiti-cloud-charts accordingly](https://github.com/Activiti/activiti-cloud-charts/pull/51/commits/6339eb87fe8ca10421b3926885044ffcadcf4a0e) and the suggested APS configuration in https://issues.alfresco.com/jira/browse/ACTIVITI-2715

**Comment by rgauss** [comment]
Thanks @ryandawsonuk!

We're working on fixing up our build and will merge once that's done.

**Pull request merged**
