### PR TITLE
AUTH-245

### PR DESCRIPTION
**Pull request by melahn**

### CODE REVIEW

**Comment by rgauss** [comment]
Do we want to amend rather than replace, or are we expecting people can just navigate to previous tags?

**Comment by kconkas** [comment]
I see the Identity Service 1.0 stories/tasks are also included in the list. I'm thinking for someone who wants to know what's new in 1.1 it would be easier if there was an easy way to get to only 1.1 related stories/tasks. Should we separate the two?

**Comment by melahn** [comment]
> Do we want to amend rather than replace, or are we expecting people can just navigate to previous tags?

@rgauss  ... I'm not completely understand your comment.   What I would prefer is a single page in master that shows all the changes introduced in each version.  Seems simpler for the user to see the history.

**Comment by svidrascu** [comment]
Please provide a task desription on the description of the merge request.

**Comment by rgauss** [comment]
> @rgauss ... I'm not completely understand your comment. What I would prefer is a single page in master that shows all the changes introduced in each version. Seems simpler for the user to see the history.

Sorry, I misread the diff in the PR, it looked like it was replacing the 1.0 change log.

**Comment by melahn** [comment]
> > @rgauss ... I'm not completely understand your comment. What I would prefer is a single page in master that shows all the changes introduced in each version. Seems simpler for the user to see the history.
> 
> Sorry, I misread the diff in the PR, it looked like it was replacing the 1.0 change log.

Yes, what was confusing is that I also got rid of the html that Jira's changelog plugin generated and instead went for real markdown which showed everything as a diff

**Pull request merged**
